version: '3.1'
services:
  credit-credits-service:
    image: 'nikitkamzgb/credit-credits-service-iso'
    container_name: 'credit-credits-service-container'
    depends_on:
      - credit-credits-db
    environment:
      - SERVER_PORT=7774
      - SPRING_DATASOURCE_URL=jdbc:postgresql://credit-credits-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=qwe
    ports:
      - 8774:7774

  credit-credits-db:
    image: 'postgres'
    container_name: 'credit-credits-db-container' 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwe
    ports:
      - 1005:5432